version: "3.8"

services:
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  node_app:
    build: .
    ports:
      - 4000:3000
    environment:
      APP_NAME: dockerexampleapp
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/mydockerapp
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
